name: j1.2

on: 
  # pull_request: {}
  push: {}
  # workflow_run:
  #   workflows: ["j1"]
  #   types:
  #     - completed
jobs:
  tests:
    uses: ./.github/workflows/1.yaml
  build:
    needs: ["tests"]
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: step 1.2
        run: echo "Job 1.2"