name: j1

on: 
  # push: {}
  workflow_call: 
    outputs:
      my-output:
        description: "The first job output"
        value: ${{ jobs.build.outputs.VALUE_1 }}

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    outputs:
      VALUE_1: ${{ steps.test.outputs.VALUE_1 }}
    steps:
      - name: step 1
        id: test
        run: echo "VALUE_1=ghcr.io/oracle-samples/oci-secrets-store-csi-driver-provider:f3c216f5a54b42787cd6e98d40da559c9740b722" >> $GITHUB_OUTPUT
      - name: Log into GitHub Container Registry
        run:  echo "${{ secrets.CR_PAT }}" | docker login ghcr.io -u ${GITHUB_ACTOR,,} --password-stdin