name: j1

on: 
  # push: {}
  workflow_call: 
    outputs:
      my-output:
        description: "The first job output"
        value: ${{ jobs.build.outputs.VALUE_1 }}

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    outputs:
      VALUE_1: ${{ steps.test.outputs.VALUE_1 }}
    steps:
      - name: step 1
        id: test
        run: echo "VALUE_1=Job 1" >> $GITHUB_OUTPUT


